################
#    _____     #
#   |     \    #
#   |      |   #
#   |____ /    #
#   |     \    #
#   |      |   #
#   |_____/    #
#              #
################

#First
Title-1: "Example1"

#Second
Title-2: "&cExample2"

#Third
Title-3: "&ePONG"

#Fourth
Title-4: "Ping"


delay: 10
